### ISSUE TITLE
Wrong iphdr and tcphdr mapping

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#2637]
### Describe the bug

https://github.com/l3af-project/eBPF-Package-Repository/pull/54 is failing which tries to use iphdr and tcphdr in cross-platform code.

https://github.com/microsoft/ebpf-for-windows/blob/main/include/net/ip.h#L94 defines it as _IPV4_HEADER, but the field names in that struct don't match the expected field names in iphdr which is causing the windows test failures in https://github.com/l3af-project/eBPF-Package-Repository/pull/54.

### Steps taken to reproduce bug

Try to compile https://github.com/l3af-project/eBPF-Package-Repository/pull/54

### Expected behavior

Build should succeed

### Actual outcome

Build fails

### Additional details

```
D:/a/eBPF-Package-Repository/eBPF-Package-Repository/ratelimiting/ratelimiting_kern.c(103,27): error G1A4676F8: no member named 'ihl' in 'struct _IPV4_HEADER' [D:\a\eBPF-Package-Repository\eBPF-Package-Repository\build\ratelimiting\ratelimiting_kern.vcxproj]
      __u8 l4_offset = iph->ihl * 4; // ipv4 header length
                       ~~~  ^
D:/a/eBPF-Package-Repository/eBPF-Package-Repository/ratelimiting/ratelimiting_kern.c(114,31): error G1A4[67](https://github.com/l3af-project/eBPF-Package-Repository/actions/runs/5384061159/jobs/9771541350?pr=54#step:5:68)6F8: no member named 'doff' in 'struct tcphdr' [D:\a\eBPF-Package-Repository\eBPF-Package-Repository\build\ratelimiting\ratelimiting_kern.vcxproj]
      __u16 data_offset = tcph->doff * 4; // tcp header length
                          ~~~~  ^
```

https://github.com/microsoft/ebpf-for-windows/blob/main/include/net/tcp.h#L11 has `data_offset` instead of `doff`

**Comment by hawkinsw** [comment]
@dthaler Do you want to add Linux-compatible field names for the IPv6 header, too, while we are at it?
