### ISSUE TITLE
Cryptic error message when exceeding max program length.

### ISSUE THREAD

**Issue by rectified95** [microsoft/ebpf-for-windows#1220]
### Describe the bug

When my eBPF program grows too long, it crashes after being loaded and outputs errors such as:
`panic: reflect: reflect.Value.Pointer on an invalid nonheap pointer.` or `error in Section 33`

### Steps taken to reproduce bug

Add eg. a bpf_printk line to a program on the verge of exceeding the limit and observe described behavior.

### Expected behavior

Ideally, I'd be notified that the program is too long at compilation time.
At a minimum, ebpf should make it clear what is happening after it crashes. 
I wouldn't have thought of the underlying cause if an experienced colleague hadn't told me.

### Actual outcome

Output not indicative of reason for the crash.

**Comment by shankarseal** [comment]
@rectified95  - this is because all functions (other than the entry functions) should be marked as  )force_inline.

I am not creating a PREvail issue as comparing the .o file of a good and bad program will reveal how in the bad case the function is not being inlined at all and a "call" instruction is emitted.

Llvm-objdump -r lists the relocation records. Relocations are places in each code segment where the loader would need to perform relocations.

There are two types of BPF relocations:
1)	Data relocations (the address of the map)
2)	Code relocations, calls to other code segments.

The verifier output could be clearer, but it is explaining what failed.
error: Unresolved external symbol authorize_v6 at location 13

This message means it found a symbol (authorize_v6) at instruction 13 that doesn’t refer to a known map (it’s a function, not a map).

Verifier should rather reject this as a wrong relocation type instead and it should also tell you what segment the failure occurred in.

If you dump the assembly of the failing section:
C:\Users\alanjo\test>llvm-objdump -Sl fail_endpoint_prog.o --section=cgroup/connect6

fail_endpoint_prog.o:   file format elf64-bpf


Disassembly of section cgroup/connect6:

0000000000000000 <authorize_connect6>:
; authorize_connect4_0():
; C:\Users\azureuser\azure-container-networking\test\ebpf\src\.\endpoint_prog.c:236
llvm-objdump.exe: warning: 'fail_endpoint_prog.o': failed to find source C:\Users\azureuser\azure-container-networking\test\ebpf\src\.\endpoint_prog.c
       0:       bf 16 00 00 00 00 00 00 r6 = r1
       1:       18 01 00 00 20 63 61 6c 00 00 00 00 6c 65 64 00 r1 = 28259014020260640 ll
; C:\Users\azureuser\azure-container-networking\test\ebpf\src\.\endpoint_prog.c:237
       3:       7b 1a f8 ff 00 00 00 00 *(u64 *)(r10 - 8) = r1
       4:       18 01 00 00 43 6f 6e 6e 00 00 00 00 65 63 74 36 r1 = 3923870462642122563 ll
       6:       7b 1a f0 ff 00 00 00 00 *(u64 *)(r10 - 16) = r1
       7:       bf a1 00 00 00 00 00 00 r1 = r10
       8:       07 01 00 00 f0 ff ff ff r1 += -16
; C:\Users\azureuser\azure-container-networking\test\ebpf\src\.\endpoint_prog.c:237
       9:       b7 02 00 00 10 00 00 00 r2 = 16
      10:       85 00 00 00 0c 00 00 00 call 12
; C:\Users\azureuser\azure-container-networking\test\ebpf\src\.\endpoint_prog.c:239
      11:       bf 61 00 00 00 00 00 00 r1 = r6
      12:       b7 02 00 00 01 00 00 00 r2 = 1
      13:       85 10 00 00 ff ff ff ff call -1
      14:       95 00 00 00 00 00 00 00 exit

As you can see, instruction 13 is a call to BPF helper -1 (as compared to the calls at instruction 10, which is to helper #12), with the expectation that -1 will be replaced with the address of authorize_v6.

eBPF doesn’t support relocatable function calls, so the verifier fails it.

**Comment by dthaler** [comment]
Question: what error message is shown on Linux for this case?
