### ISSUE TITLE
Setup-DevEnv.ps1 fails to install WDK.VSIX

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1404]
jsturtevant posted the following on the ebpf-for-windows slack channel:

```I've followed the instructions at https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#building-ebpf-for-windows and can't seem to get the project to build I have multiple errors like:
"C:\Users\azureuser\ebpf-for-windows\ebpf-for-windows.sln" (default target) (1) ->
       "C:\Users\azureuser\ebpf-for-windows\netebpfext\netebpfext.vcxproj.metaproj" (default target) (12) ->
       "C:\Users\azureuser\ebpf-for-windows\netebpfext\netebpfext.vcxproj" (default target) (23) ->
       (PrepareForBuild target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDr
       iver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the P
       roject menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\azureuser\ebpf-for-windows\netebpfext\netebpfext.vcxproj]
I think i have this installed (I used the script at https://github.com/microsoft/ebpf-for-windows/blob/main/scripts/Setup-DevEnv.ps1)  and see on the machine.  I've also tried doing the "retarget solution" in VS with no luck
What am I missing?  I am running on Windows 11 if that makes a difference```

**Comment by Alan-Jowett** [comment]
Additional data:
This is an Azure Windows 11 VM image that has VS2022 pre-installed. 
Confirmed the WDK is installed and tools are present, but for some reason, the build environment isn't finding them.

**Comment by jsturtevant** [comment]
I reproduced the same issue from a Windows 10 machine, it seems related to having different VS sets of tools:

![image](https://user-images.githubusercontent.com/648372/191347361-fab44979-ddf2-48c6-b109-00efc8cfeb25.png)

When launching the VS developer prompt from within VS (not from the build tools installation) I don't get this error but do get some other errors:

```
 C:\Users\azureuser\ebpf-for-windows\x64\Debug\bindmonitor_driver.c : fatal error C1041: cannot open program da
       tabase 'C:\Users\azureuser\ebpf-for-windows\x64\Debug\x64\Debug\vc142.pdb'; if multiple CL.EXE write to the same
        .PDB file, please use /FS [C:\Users\azureuser\ebpf-for-windows\x64\Debug\bindmonitor.vcxproj] [C:\Users\azureus
       er\ebpf-for-windows\tests\sample\sample.vcxproj]
         C:\Users\azureuser\ebpf-for-windows\x64\Debug\bindmonitor_driver.c : fatal error C1041: cannot open program da
       tabase 'C:\Users\azureuser\ebpf-for-windows\x64\Debug\x64\Debug\vc142.pdb'; if multiple CL.EXE write to the same
        .PDB file, please use /FS [C:\Users\azureuser\ebpf-for-windows\x64\Debug\bindmonitor.vcxproj] [C:\Users\azureus
       er\ebpf-for-windows\tests\sample\sample.vcxproj]
         C:\Users\azureuser\ebpf-for-windows\x64\Debug\.vcxproj(1,1022): error MSB4025: The project file could not be l
       oaded. The 'VCProjectVersion' start tag on line 1 position 999 does not match the end tag of 'VCP'. Line 1, posi
       tion 1022. [C:\Users\azureuser\ebpf-for-windows\tests\sample\sample.vcxproj]
         C:\Users\azureuser\ebpf-for-windows\x64\Debug\.vcxproj(1,1022): error MSB4025: The project file could not be l
       oaded. The 'VCProjectVersion' start tag on line 1 position 999 does not match the end tag of 'VCP'. Line 1, posi
       tion 1022. [C:\Users\azureuser\ebpf-for-windows\tests\sample\sample.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.ta
       rgets(241,5): error MSB8066: Custom build for 'bad_map_name.c;bindmonitor.c;bindmonitor_ringbuf.c;bindmonitor_ta
       ilcall.c;bpf_call.c;cgroup_sock_addr.c;decap_permit_packet.c;divide_by_zero.c;droppacket.c;encap_reflect_packet.
       c;map.c;map_in_map.c;map_in_map_v2.c;map_reuse.c;map_reuse_2.c;pidtgid.c;printk.c;printk_legacy.c;reflect_packet
       .c;sockops.c;tail_call.c;tail_call_bad.c;tail_call_map.c;tail_call_multiple.c;test_sample_ebpf.c;test_utility_he
       lpers.c;unsafe\droppacket_unsafe.c;unsafe\empty.c;unsafe\invalid_helpers.c;unsafe\invalid_maps1.c;unsafe\invalid
       _maps2.c;unsafe\invalid_maps3.c;unsafe\printk_unsafe.c;custom_program_type\bpf.c' exited with code -1. [C:\Users
       \azureuser\ebpf-for-windows\tests\sample\sample.vcxproj]
```

**Comment by jsturtevant** [comment]
I was able to get it to build using VS 2019 via "build" UI, the command prompt worked after building in VS.  

Went back to Windows 11 machine and still not working but I may need to start fresh.

**Comment by jsturtevant** [comment]
I got it working on windows 11 using the cmd prompt by launching via 
![image](https://user-images.githubusercontent.com/648372/191355391-4706b713-61ad-49b3-ba22-3685231ae6d3.png)

I think the step at https://github.com/microsoft/ebpf-for-windows/blob/d60725f04ed670be9171cc6ab666f79af932c0cc/scripts/Setup-DevEnv.ps1#L10 installs a second instance which the WDK doesn't get added and so fails
