### ISSUE TITLE
Catch2 submodule update triggers test failures

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#4938]
## Summary
Updating the Catch2 submodule from `b62413a` to `de7e863` (as proposed in PR #4933) triggers test failures that do not occur on main branch.

### 1. Static Analysis Error (analyze / build Debug)
- **File:** `libs/runtime/unit/platform_unit_test.cpp` line 1786
- **Error:** `error C6001: Using uninitialized memory 'reserved_data'`
- **Context:** This appears to be a false positive - the variable is set by `ebpf_ring_buffer_reserve()` and checked for null before use

### 2. Unit Test Failure (unit_tests / run_test Release)
- **File:** `tests/unit/wer_report_test_wrapper.cpp` lines 80, 171, 213
- **Error:** Test expects `"Test Application Hang"` but gets `"Test Application Crash"`
- **Details:**
  - 2 test cases failed out of 373
  - 4 assertions failed out of 1,012,631

## Reproduction
These failures occur in PR #4933 CI runs but pass on the main branch.

## Catch2 Commits Being Added
The update includes these Catch2 changes:
- `de7e863` - Clang on Windows _MSC_VER fix
- `024aec9` - Add efficient skip forward to Values, Map and Take generators
- `9eca713` - Add option to skip forward to generator interface
- `44c597f` - Add Concat generator
- `6aedc79` - Remove unused m_used_up member in ChunkGenerator
- `fcbf006` - Fix _NullFile for MinGW
- `2580ead` - Add UNSCOPED_CAPTURE
- `b59f4f3` - Rename DEPRECATED -> CATCH_DEPRECATED
- And more...

## Investigation Needed
- Determine why updating Catch2 affects static analysis warnings
- Determine why WER report tests fail with new Catch2 version
- The `DEPRECATED -> CATCH_DEPRECATED` rename may affect code using the old macro

## Related
- PR #4933 - Dependabot PR that bumps Catch2 and pe-parse submodules
- Workflow run: https://github.com/microsoft/ebpf-for-windows/actions/runs/21318903928
